
# catalog-info.yml
# This file contains metadata for backstage
# Read more about available fields and annotations:
# https://github.com/tradeshift/backstage
#
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tradeshift-ubl-xsd
  description: |
    XSDs for Universal Business Language
  annotations:
    github.com/project-slug: Tradeshift/tradeshift-ubl-xsd # GitHub project name
    sentry.io/project-slug: tradeshift-ubl-xsd # Name in sentry for enabling Sentry integration
    backstage.io/kubernetes-id: tradeshift-ubl-xsd # Kubernetes app id, this is a Kubernetes label from the deployment of your service look for ex. app: backstage
    # pagerduty.com/integration-key: a834115a04c748a5befc777442e209b8 # PagerDuty integration id from the service. Can be created in Pagerduty under Service Discovery -> Service name -> Integrations tab -> Add new integration. Please use the Events API v2, this might require you to chnage 'Alert and Incident Settings' on the 'Integrations tab' page.
    sonarqube.org/project-key: tradeshift-ubl-xsd # Name of the project in SonarQube
  tags:
    - java
spec:
  type: other
  owner: backend-service-committers
  lifecycle: experimental
